---
title: "500 Main Page for Spring 2021"
---

Welcome! PQHS 500 (also called CRSP 500) is taught by Professor Thomas Love in the Department of Population and Quantitative Health Sciences at Case Western Reserve University. Everything that Professor Love will provide to help you with the course will appear on this website.

The class will be held on Thursdays from 8:30 - 11:00 AM virtually, using the Zoom platform, starting on 2021-02-04. Information on the Zoom meetings will be found on [Canvas](https://canvas.case.edu). Registration for the course is required.

## Everything You Need Is Here

The menu bar includes links to everything you'll need this semester, including

- the [course syllabus](https://thomaselove.github.io/500-2021-syllabus/)
- the [course calendar](calendar.html), which provides the final word on all deadlines, and also provides links to the materials used in each class session
- detailed information on all [course assignments](https://thomaselove.github.io/500/project.html), including labs, essays, the Observational Studies in Action presentations of studies from the literature, and a semester-long course project.
    - All deadlines for these assignments appear in the [calendar](calendar.html).
- information on [installing R and RStudio](software_install.html), installing [key R packages](r_packages.html), and [downloading data (and code)](data_index.html) you'll need for the class, as well as a [review of some useful R basics](https://github.com/THOMASELOVE/500-2021/tree/master/r-basics).
- a link to the [Canvas](https://canvas.case.edu/) system (log-in required) we use to communicate information about Zoom sessions, and for turning in some assignments
- information about where you can [get help and contact us](contact.html).

## What Should I Do Before Class Begins?

1. **Buy the book**. During the course, we will read Paul Rosenbaum's book **Observation and Experiment: An Introduction to Causal Inference**, which is available as an e-book or in paperback for under $25. Please buy the book and read the Preface and Chapter 1 before our first class on 2020-02-04.

2. **Download the software**. Install R and RStudio and some necessary R packages on a computer you can control throughout the semester. Details [are available here](software_install.html).

#### This site last updated `r Sys.time()`
